# Generated by Django 6.0.6 on 2026-07-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_recruiter_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_verification_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_verification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_ai_verified',
            field=models.BooleanField(default=False),
        ),
    ]
