# core/anomaly_detection.py
# Complete Anomaly Detection Pipeline for Talent Shield

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from datetime import datetime, timedelta
import re
import logging
from typing import Dict, List, Tuple, Any

logger = logging.getLogger(__name__)


class AnomalyDetectionPipeline:
    """
    Complete Anomaly Detection Pipeline for Talent Shield
    Detects: Fraudulent Jobs, Fake CVs, Suspicious Users, Unusual Patterns
    """
    
    def __init__(self):
        """Initialize the anomaly detection pipeline"""
        logger.info("Initializing Anomaly Detection Pipeline...")
        
        self.scaler = StandardScaler()
        self.isolation_forest = IsolationForest(
            contamination=0.1,
            random_state=42,
            n_estimators=100
        )
        self.tfidf = TfidfVectorizer(max_features=100)
        self.is_trained = False
        
        # Suspicious patterns database
        self.suspicious_keywords = {
            'job': [
                'pay immediately', 'wire transfer', 'free money',
                'limited time', 'urgent', 'confidential',
                'bank account', 'credit card', 'ssn',
                'no experience', 'unlimited earning',
                'work from home', 'immediate start',
                'password', 'send money', 'deposit',
                'activation fee', 'processing fee',
                'guaranteed income', 'make money fast',
                'easy money', 'get rich', 'earn fast',
                'no interview', 'guaranteed job'
            ],
            'cv': [
                'generated by AI', 'chatgpt', 'copied from',
                'template cv', 'generic', 'placeholder',
                'lorem ipsum', 'sample cv', 'dummy',
                'ai generated', 'language model',
                'cv template', 'example cv'
            ],
            'user': [
                'suspicious activity', 'rapid clicks', 'bot detected',
                'unusual pattern', 'multiple accounts'
            ]
        }
        
        # Normal patterns database
        self.normal_patterns = {
            'job_salary_range': (30000, 200000),
            'job_description_length': (100, 2000),
            'cv_skill_count': (2, 10),
            'cv_experience_range': (0, 20),
            'user_activity_pattern': (1, 50),
            'applications_per_day': (1, 10)
        }
        
        logger.info("✅ Anomaly Detection Pipeline initialized")
        print("✅ Anomaly Detection Pipeline initialized!")

    # ============================================================
    # JOB FRAUD DETECTION
    # ============================================================
    
    def detect_job_fraud(self, job_data: Dict) -> Dict:
        """
        Detect fraudulent job postings
        Returns: Fraud score (0-100), Risk Level, Reasons
        """
        fraud_score = 100
        reasons = []
        
        description = job_data.get('description', '').lower()
        title = job_data.get('title', '').lower()
        
        # 1. Check for suspicious keywords
        suspicious_count = 0
        for keyword in self.suspicious_keywords['job']:
            if keyword in description or keyword in title:
                suspicious_count += 1
                reasons.append(f"Suspicious keyword found: '{keyword}'")
        
        if suspicious_count > 0:
            fraud_score -= suspicious_count * 5
        
        # 2. Check salary range
        salary = job_data.get('salary', '')
        if salary:
            try:
                salary_num = int(str(salary).replace(',', '').replace('$', ''))
                if salary_num < self.normal_patterns['job_salary_range'][0]:
                    fraud_score -= 20
                    reasons.append(f"Salary too low: {salary}")
                elif salary_num > self.normal_patterns['job_salary_range'][1] * 3:
                    fraud_score -= 30
                    reasons.append(f"Suspiciously high salary: {salary}")
            except:
                pass
        
        # 3. Check description length
        desc_length = len(description)
        if desc_length < self.normal_patterns['job_description_length'][0]:
            fraud_score -= 15
            reasons.append("Description too short")
        elif desc_length > self.normal_patterns['job_description_length'][1] * 3:
            fraud_score -= 10
            reasons.append("Description suspiciously long")
        
        # 4. Check company name
        company = job_data.get('company', '').lower()
        generic_companies = ['company', 'private', 'confidential', 'anonymous', 'unknown']
        if any(gc in company for gc in generic_companies):
            fraud_score -= 15
            reasons.append("Generic company name")
        
        # 5. Check email domain
        email = job_data.get('email', '')
        if email:
            suspicious_domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'protonmail.com']
            if any(sd in email for sd in suspicious_domains):
                fraud_score -= 10
                reasons.append("Suspicious email domain")
        
        # 6. Check for payment requests
        payment_keywords = ['fee', 'pay', 'deposit', 'cost', 'charge', 'money', 'payment']
        for pk in payment_keywords:
            if pk in description:
                fraud_score -= 15
                reasons.append(f"Asks for payment: '{pk}'")
                break
        
        # Determine risk level
        fraud_score = max(0, min(100, fraud_score))
        
        if fraud_score >= 80:
            risk_level = 'Low'
        elif fraud_score >= 60:
            risk_level = 'Medium'
        else:
            risk_level = 'High'
        
        return {
            'fraud_score': fraud_score,
            'risk_level': risk_level,
            'reasons': reasons[:5],
            'is_fraud': fraud_score < 50
        }

    # ============================================================
    # CV ANOMALY DETECTION
    # ============================================================
    
    def detect_cv_anomaly(self, cv_text: str) -> Dict:
        """
        Detect anomalous/fake CVs
        Returns: Anomaly score (0-100), Risk Level, Reasons
        """
        anomaly_score = 100
        reasons = []
        
        if not cv_text:
            return {
                'anomaly_score': 50,
                'risk_level': 'Unknown',
                'reasons': ['No text provided'],
                'is_anomaly': False,
                'word_count': 0,
                'skill_count': 0
            }
        
        text_lower = cv_text.lower()
        
        # 1. Check for AI/ChatGPT markers
        ai_markers = ['chatgpt', 'ai generated', 'generated by ai', 'large language model', 'llm']
        for marker in ai_markers:
            if marker in text_lower:
                anomaly_score -= 25
                reasons.append(f"AI generation detected: '{marker}'")
                break
        
        # 2. Check for generic placeholders
        placeholders = ['lorem ipsum', 'sample text', 'dummy data', 'placeholder', 'example text']
        for ph in placeholders:
            if ph in text_lower:
                anomaly_score -= 20
                reasons.append(f"Placeholder text detected: '{ph}'")
                break
        
        # 3. Check word count
        word_count = len(cv_text.split())
        if word_count < 50:
            anomaly_score -= 30
            reasons.append(f"CV too short: {word_count} words")
        elif word_count < 200:
            anomaly_score -= 10
            reasons.append(f"CV unusually short: {word_count} words")
        
        # 4. Check for repeated patterns
        if self._detect_repeated_text(cv_text):
            anomaly_score -= 15
            reasons.append("Repeated text detected")
        
        # 5. Check skill count
        skill_count = self._count_skills(cv_text)
        if skill_count < 2:
            anomaly_score -= 20
            reasons.append(f"Too few skills: {skill_count}")
        elif skill_count > 20:
            anomaly_score -= 10
            reasons.append(f"Suspiciously many skills: {skill_count}")
        
        # Determine risk level
        anomaly_score = max(0, min(100, anomaly_score))
        
        if anomaly_score >= 80:
            risk_level = 'Low'
        elif anomaly_score >= 60:
            risk_level = 'Medium'
        else:
            risk_level = 'High'
        
        return {
            'anomaly_score': anomaly_score,
            'risk_level': risk_level,
            'reasons': reasons[:5],
            'is_anomaly': anomaly_score < 50,
            'word_count': word_count,
            'skill_count': skill_count
        }

    # ============================================================
    # USER ANOMALY DETECTION
    # ============================================================
    
    def detect_user_anomaly(self, user_data: Dict) -> Dict:
        """
        Detect suspicious user behavior
        Returns: Anomaly score (0-100), Risk Level, Reasons
        """
        anomaly_score = 100
        reasons = []
        
        # 1. Check activity count
        activity_count = user_data.get('activity_count', 0)
        if activity_count > 100:
            anomaly_score -= 20
            reasons.append(f"Unusually high activity: {activity_count}")
        elif activity_count > 50:
            anomaly_score -= 10
            reasons.append(f"High activity: {activity_count}")
        
        # 2. Check applications per day
        applications_per_day = user_data.get('applications_per_day', 0)
        if applications_per_day > 20:
            anomaly_score -= 20
            reasons.append(f"Suspiciously many applications: {applications_per_day}/day")
        elif applications_per_day > 10:
            anomaly_score -= 10
            reasons.append(f"High applications: {applications_per_day}/day")
        
        # 3. Check IP country
        ip_country = user_data.get('ip_country', '')
        if ip_country and ip_country not in ['NP', 'Nepal']:
            anomaly_score -= 15
            reasons.append(f"Foreign IP detected: {ip_country}")
        
        # 4. Check for rapid registration
        registration_time = user_data.get('registration_time')
        if registration_time:
            try:
                from datetime import datetime
                if isinstance(registration_time, str):
                    reg_time = datetime.fromisoformat(registration_time)
                else:
                    reg_time = registration_time
                
                hours_since = (datetime.now() - reg_time).total_seconds() / 3600
                if hours_since < 1 and activity_count > 20:
                    anomaly_score -= 15
                    reasons.append("Suspicious: many actions in short time")
            except:
                pass
        
        # Determine risk level
        anomaly_score = max(0, min(100, anomaly_score))
        
        if anomaly_score >= 80:
            risk_level = 'Low'
        elif anomaly_score >= 60:
            risk_level = 'Medium'
        else:
            risk_level = 'High'
        
        return {
            'anomaly_score': anomaly_score,
            'risk_level': risk_level,
            'reasons': reasons[:5],
            'is_anomaly': anomaly_score < 50
        }

    # ============================================================
    # MACHINE LEARNING ANOMALY DETECTION
    # ============================================================
    
    def train_anomaly_model(self, training_data: pd.DataFrame) -> bool:
        """
        Train Isolation Forest model on normal data
        """
        try:
            if len(training_data) < 10:
                logger.warning(f"Need at least 10 samples. Got {len(training_data)}")
                return False
            
            features = self._extract_ml_features(training_data)
            scaled_features = self.scaler.fit_transform(features)
            
            self.isolation_forest.fit(scaled_features)
            
            if 'cv_text' in training_data.columns:
                texts = training_data['cv_text'].fillna('').astype(str)
                self.tfidf.fit(texts)
            
            self.is_trained = True
            logger.info(f"✅ Anomaly detection model trained on {len(training_data)} samples")
            print(f"✅ Anomaly detection model trained on {len(training_data)} samples")
            return True
            
        except Exception as e:
            logger.error(f"Training failed: {e}")
            print(f"❌ Training failed: {e}")
            return False
    
    def predict_anomaly(self, data_point: pd.DataFrame) -> Dict:
        """
        Predict if a data point is anomalous
        """
        if not self.is_trained:
            return {
                'is_anomaly': False,
                'confidence': 0,
                'message': 'Model not trained yet'
            }
        
        try:
            features = self._extract_ml_features(data_point)
            scaled_features = self.scaler.transform(features)
            
            prediction = self.isolation_forest.predict(scaled_features)
            score = self.isolation_forest.score_samples(scaled_features)
            
            is_anomaly = prediction[0] == -1
            
            return {
                'is_anomaly': is_anomaly,
                'confidence': abs(score[0]),
                'message': 'Anomaly detected!' if is_anomaly else 'Normal pattern'
            }
            
        except Exception as e:
            logger.error(f"Prediction failed: {e}")
            return {
                'is_anomaly': False,
                'confidence': 0,
                'message': f'Error: {e}'
            }

    # ============================================================
    # HELPER FUNCTIONS
    # ============================================================
    
    def _count_skills(self, text: str) -> int:
        """Count cybersecurity skills in text"""
        skills = [
            'network', 'security', 'firewall', 'vpn', 'encryption',
            'cryptography', 'linux', 'windows', 'python', 'java',
            'sql', 'database', 'web', 'cloud', 'aws', 'azure',
            'docker', 'kubernetes', 'incident', 'response',
            'forensic', 'malware', 'pentest', 'ethical', 'hacking',
            'ids', 'ips', 'soc', 'siem', 'splunk', 'qradar'
        ]
        count = 0
        text_lower = text.lower()
        for skill in skills:
            if skill in text_lower:
                count += 1
        return count
    
    def _detect_repeated_text(self, text: str) -> bool:
        """Detect if text has repeated patterns"""
        lines = [line.strip() for line in text.split('\n') if line.strip()]
        if len(lines) > 20:
            unique_lines = set(lines)
            repetition_rate = 1 - (len(unique_lines) / len(lines))
            return repetition_rate > 0.5
        return False
    
    def _extract_ml_features(self, data: pd.DataFrame) -> np.ndarray:
        """Extract features for ML models"""
        features = []
        
        for _, row in data.iterrows():
            feature_vector = [
                len(str(row.get('text', ''))) if pd.notna(row.get('text')) else 0,
                row.get('skill_count', 0) if pd.notna(row.get('skill_count')) else 0,
                row.get('experience_years', 0) if pd.notna(row.get('experience_years')) else 0,
                row.get('activity_count', 0) if pd.notna(row.get('activity_count')) else 0,
                row.get('applications', 0) if pd.notna(row.get('applications')) else 0
            ]
            features.append(feature_vector)
        
        return np.array(features)
    