# Generated by Django 6.0.6 on 2026-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='cv_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
