# Generated by Django 6.0.6 on 2026-06-24 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('challenge_master', 'Challenge Master'), ('certification_verified', 'Certification Verified'), ('fraud_free', 'Fraud-Free Profile'), ('top_performer', 'Top Performer'), ('skill_expert', 'Skill Expert'), ('quick_learner', 'Quick Learner')], max_length=50)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('points_bonus', models.IntegerField(default=0)),
                ('requirements', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('network_security', 'Network Security'), ('web_security', 'Web Security'), ('cryptography', 'Cryptography'), ('incident_response', 'Incident Response'), ('threat_analysis', 'Threat Analysis'), ('ethical_hacking', 'Ethical Hacking'), ('forensics', 'Digital Forensics'), ('compliance', 'Compliance & Risk')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('question', models.TextField()),
                ('scenario', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('answer_type', models.CharField(default='text', max_length=20)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('points', models.IntegerField(default=10)),
                ('time_limit_seconds', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['difficulty', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gamification.challenge')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('challenges_attempted', models.IntegerField(default=0)),
                ('challenges_passed', models.IntegerField(default=0)),
                ('challenges_failed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('badges', models.JSONField(default=list)),
                ('badges_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.achievement')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('candidate', 'achievement')},
            },
        ),
    ]
