# Generated by Django 6.0.6 on 2026-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('challenge_master', 'Challenge Master'), ('certification_verified', 'Certification Verified'), ('fraud_free', 'Fraud-Free Profile'), ('top_performer', 'Top Performer'), ('skill_expert', 'Skill Expert'), ('quick_learner', 'Quick Learner'), ('streak_master', 'Streak Master')], max_length=50),
        ),
    ]
