# Generated by Django 6.0.6 on 2026-06-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_achievement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamificationprofile',
            options={'ordering': ['-total_points']},
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='cv_boost_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
